var miCanvas1 = document.getElementById("miCanvas1");
var miCanvas2 = document.getElementById("miCanvas2");
var miCanvas3 = document.getElementById("miCanvas3");
var contexto1 = miCanvas1.getContext("2d");
var contexto2 = miCanvas2.getContext("2d");
var contexto3 = miCanvas3.getContext("2d");
contexto1.fillStyle = "blue";
contexto1.fillRect(0, 0, 25, 25);
contexto2.fillStyle = "green";
contexto2.fillRect(0, 0, 50, 50);
contexto3.fillStyle = "red";
contexto3.fillRect(0, 0, 75, 75);
